### ISSUE TITLE
Bias at codons ending in A

### ISSUE THREAD

**Issue by xinyangbing** [elisadonnard/riboEPAsite#1]
Hi Elisa,
I tested my ribosome profiling libraries using this program last year. My co-authors are saying now that they notice a weird decrease in occupancy at E site for all codons ending in A in only the mutants. Could you think of any possible reason why this could happen from the pipeline standpoint? I wrecked my brain thinking about possibilities of my library construction, etc, but couldn't think of anything. I tried reading through your scripts but obviously didn't find anything that stood out that would cause this bias. Could we even trust the E-site readouts anyways? Please help! 
Best,
David

**Comment by elisadonnard** [comment]
Hi David! I can definitely take a look at this and make sure there is nothing wrong on the pipeline side, can you send me more details by email and point me to the data?
best
Elisa

**Comment by elisadonnard** [comment]
Hi David, I did not see this bias in the results after running your samples, have sent you an email with more details, closing this issue now. I made some edits to the Rscripts because the input was too hardcoded. 
best 
E
